volumes:
  config:
  data_you_want_to_see_in_filebrowser:
    external: true

services:
  filebrowser:
    image: hurlenko/filebrowser
    #user: "${UID}:${GID}"
    ports:
      - 8383:8080
    volumes:
      - config:/config
      - data_you_want_to_see_in_filebrowser:/data/
    environment:
      - FB_BASEURL=/filebrowser
    restart: unless-stopped
